# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.configuration-cache=true

# 1. Disable constraints to stop the "isVisible" deprecation warnings
android.dependency.useConstraints=false

# 2. Disable experimental flags for better plugin compatibility with AGP 9.0
android.newDsl=true
android.builtInKotlin=true

# 3. Performance and AGP 9.0 defaults
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.enableAppCompileTimeRClass=true
android.usesSdkInManifest.disallowed=true
android.uniquePackageNames=true
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true